const introText = [
    "I’m Amine Elmoufid, 23 years old.",
    "On paper, my background is in finance. I am a master’s student in Financial Engineering from Meknès, Morocco.",
    "I worked with the five-star Mövenpick Marrakech as a Community Manager.",
    "I discovered the world of marketing without certificates or credentials, only with curiosity and determination.",
    "I see myself as half-engineer, half-artist.",
    "I design campaigns from concept to execution.",
    "I create identities that feel cinematic and precise.",
    "I value originality more than repetition.",
    "I see marketing as an architecture, each decision shaped by message, originality, and cultural depth.",
    "I believe a brand is not decoration, but a message translated into story.",
    "I build slowly, but deliberately.",
    "I seek collaboration where depth and creativity matter.",
    "What defines me is the fusion of both worlds, the discipline of finance meeting the imagination of branding, a combination I carry into everything I create."
];
const portfolioData = [
  { id: 1, title: "Project 1", content: "Content for project 1.1" },
  { id: 2, title: "Project 2", content: "Content for project 2" },
  { id: 3, title: "Project 3", content: "Content for project 3" },
  { id: 4, title: "Project 4", content: "Content for project 4" },
  { id: 5, title: "Project 5", content: "Content for project 5" },
  { id: 6, title: "Project 6", content: "Content for project 6" },
  { id: 7, title: "Project 7", content: "Content for project 7" },
  { id: 8, title: "Project 8", content: "Content for project 8" },
  { id: 9, title: "Project 9", content: "Content for project 9" },
  { id: 10, title: "Project 10", content: "Content for project 10" },
  { id: 11, title: "Project 11", content: "Content for project 11" },
  { id: 12, title: "Project 12", content: "Content for project 12" },
  { id: 13, title: "Project 13", content: "Content for project 13" },
  { id: 14, title: "Project 14", content: "Content for project 14" },
  { id: 15, title: "Project 15", content: "Content for project 15" },
  { id: 16, title: "Project 16", content: "Content for project 16" },
  { id: 17, title: "Project 17", content: "Content for project 17" },
  { id: 18, title: "Project 18", content: "Content for project 18" },
  { id: 19, title: "Project 19", content: "Content for project 19" },
  { id: 20, title: "Project 20", content: "Content for project 20" },
  { id: 21, title: "Project 21", content: "Content for project 21" },
  { id: 22, title: "Project 22", content: "Content for project 22" },
  { id: 23, title: "Project 23", content: "Content for project 23" }
];